### ISSUE TITLE
Status update push failure SPAM

### ISSUE THREAD

**Issue by gadnis** [buckaroo-it/PrestaShop#161] opened 2024-04-29 06:05 UTC
Hi,

Each time a customer failed to pay for an order than we get repetitive emails from buckaroo-mailservice.nl with message that our webshop could not be informed via an automated push message. [screenshot](https://prnt.sc/QkIgvDTb8B3M)

Is it possible to return response for the buckaroo that webshop is aware of failed payment instead of returning `Status code: 503 (ServiceUnavailable)` ? [query string](https://prnt.sc/7oLAH93J5IFL) pushed to `index.php?fc=module&module=buckaroo3&controller=return` (I removed `brq_transactions`, `brq_websitekey`, `brq_signature`)

**Comment by Buckaroo-Rene** [comment] 2024-04-30 14:47
Hi @gadnis,

I've noticed in the Buckaroo Plaza at "Settings" -> "Website keys" that you've configured the PUSH URL there with http instead of https. This was causing the issue of the PUSH not being received correctly.
The plugin itself is sending the correct PUSH URL. Can you double check if the issue is now resolved?

Please let me know.

![Screenshot 2024-04-30 093938](https://github.com/buckaroo-it/PrestaShop/assets/105488705/930bf28f-d48c-4e43-956f-56f3fdf61631)

**Comment by Buckaroo-Rene** [comment] 2024-05-02 08:04
Hi @gadnis ,

Plese let us know if the issue persists.
For now I have closed this issue.

Best regards,
René

**Closed** 2024-05-02 08:03 UTC
Labels: Status: Waiting for info, Priority: Normal

**Comment by gadnis** [comment] 2024-05-02 08:39
Hi, @Buckaroo-Rene 

I don't remember if it was http or https but now I see it's https in "Settings" -> "Websites" general tab and it's empty values in Push Settings tab in the field `Push URI Success/Pending` and others [screenshot](https://prnt.sc/VTDXiUE_BqeC). 
Is it OK or should it be filled?

**Comment by Buckaroo-Rene** [comment] 2024-05-02 08:48
Hi @gadnis,

It is ok to leave it empty because the Buckaroo plugin is also sending the correct PUSH URL's in the requests to Buckaroo.
You can open any transaction in the Buckaroo Plaza and look at the XML log tab.
Here you can see the request and you'll see that the  "PushURL":  is being send with your website URL.

Please just double check if orders in PrestaShop are being updated automatically. Then you are good to go.

One more thing I noticed is that you have a setting configured from Buckaroo that for every order that succeeds you are getting an e-mail. This can then be disabled I think as well because PrestaShop's orders are automatically being updated with the correct status with the PUSH. But the e-mail can be a personal preference ofcourse.
You can turn that e-mail notification off in your website settings in Buckaroo, see below (marked in yellow):
![image](https://github.com/buckaroo-it/PrestaShop/assets/105488705/d7086dd2-6963-430f-b107-59197d7cb02f)

Best regards,
René
